POST http://localhost:3000/events
content-type: application/json
authorization: 

{
  "name": "TestName",
  "description": "TestDescription",
  "location": "TestLocation",
  "dateTime": "2025-01-01T15:30:00.000Z"
}